{
    "repos": [
        {
            "hooks": [
                {
                    "id": "end-of-file-fixer"
                },
                {
                    "id": "check-yaml"
                },
                {
                    "id": "check-added-large-files"
                },
                {
                    "args": [
                        "--branch",
                        "master",
                        "--branch",
                        "main",
                        "--branch",
                        "production"
                    ],
                    "id": "no-commit-to-branch"
                }
            ],
            "repo": "https://github.com/pre-commit/pre-commit-hooks",
            "rev": "v3.2.0"
        },
        {
            "hooks": [
                {
                    "entry": "nix-fmt",
                    "files": "^.*\\.nix$",
                    "id": "nix-fmt",
                    "language": "script",
                    "name": "Format nix files"
                }
            ],
            "repo": "local"
        }
    ]
}