keys:
  - &biome-fest age18t59p33fjxw3xklt0wyaxtel6wqy4q8c7428kj0xaqxpsg4nhf7q4ex6vk
  - &blind-spots age1zyvzu2fhz8597af987h74ypty09lgdl82ts79lhxh7muu6z5zp8q87ndpd
creation_rules:
  - path_regex: biome-fest.yaml$
    key_groups:
    - age:
      - *biome-fest
  - path_regex: blind-spots.yaml$
    key_groups:
    - age:
      - *blind-spots