keys:
  - &biome-fest age1h255jqgystcpptqq205u8l2jfvpkwx5hn25mgtydr92v95pymf4swh9n4q
  - &blind-spots age1zyvzu2fhz8597af987h74ypty09lgdl82ts79lhxh7muu6z5zp8q87ndpd
creation_rules:
  - path_regex: biome-fest.yaml$
    key_groups:
    - age:
      - *biome-fest
  - path_regex: blind-spots.yaml$
    key_groups:
    - age:
      - *blind-spots
