# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ pkgs, config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" "i915" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7aefc206-56e9-4426-a19e-f215dc813886";
      fsType = "ext4";
    };

  boot.initrd = {
    luks.devices."luks-ff0fdffe-9e8d-4956-92ef-ce2317629a32" = {
      device = "/dev/disk/by-uuid/ff0fdffe-9e8d-4956-92ef-ce2317629a32";
      # About key enrolling: https://nixos.org/manual/nixos/stable/#sec-luks-file-systems-fido2
      # crypttabExtraOpts = [ "fido2-device=auto" ];
    };
    systemd.enable = true;
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8DFC-47EE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ {
    device = "/var/lib/swapfile";
    size = 16*1024;
  } ];

  # Plymouth boot animation
  boot = {
    plymouth.enable = true;

    # Enable "Silent Boot"
    consoleLogLevel = 0;
    kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"
      "loglevel=3"
      "rd.systemd.show_status=false"
      "rd.udev.log_level=3"
      "udev.log_priority=3"
    ];
    # Hide the OS choice for bootloaders.
    # It's still possible to open the bootloader list by pressing any key
    # It will just not appear on screen unless a key is pressed
    loader.timeout = 0;
  };
  boot.initrd.verbose = false;

  # Enable bluetooth
  hardware.bluetooth.enable = true;

  nixpkgs.config.allowUnfree = true;

  # Power management using auto-cpufreq
  powerManagement.enable = true; # basic NixOS powermanagement
  services.auto-cpufreq.enable = true;
  services.tlp.enable = false; # Wiki says so to avoid conflicts
  services.auto-cpufreq.settings = {
    # battery = {
    #   governor = "powersave";
    #   turbo = "never";
    #   scaling_max_freq = 8800000; # I'd rather wait a bit than have battery drain
    # };
    battery = {
      governor = "performance";
      turbo = "always"; # Turbo should be used on charger
    };
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "23.11"; # Did you read the comment?
}
